site_name: Armory
repo_url: https://github.com/stablekernel/armory
pages:
  - Home: index.md
  - Quickstart: quickstart.md
  - Components: components.md
  - Conveniences: conveniences.md
  - Robots: robots.md
  - Documentation: https://stablekernel.github.io/Armory/documentation/index.html
theme: readthedocs