site_name: Armory
repo_url: https://github.com/stablekernel/armory
pages:
  - Home: index.md
  - Overview: overview.md
  - Quickstart: quickstart.md
  - Components: components.md
  - Conveniences: conveniences.md
  - Robots: robots.md
  - Documentation: documentation/index.md
theme: readthedocs